#ifndef __SYSCALLNUMBERS_H__
#define __SYSCALLNUMBERS_H__

/*** Syscall from console.h ***/
#define SYSCALL_SETCURSOR   100
#define SYSCALL_GETCURSOR   101
#define SYSCALL_PRINTSTR    102
#define SYSCALL_CLEARSCREEN 103
#define SYSCALL_GETCH       104

/*** Syscall from rtc.h ***/
#define SYSCALL_READRTCTIME 200
#define SYSCALL_READRTCDATE 201

/*** Syscall from task.h ***/
#define SYSCALL_CREATETASK           300
#define SYSCALL_GETCURRENTTASKID     301
#define SYSCALL_SCHEDULE             302
#define SYSCALL_CHANGETASKPRIORITY   303
#define SYSCALL_CHANGETASKAFFINITY   304
#define SYSCALL_WAITTASK             305
#define SYSCALL_NOTIFYTASK           306
#define SYSCALL_ENDTASK              307
#define SYSCALL_EXIT                 308
#define SYSCALL_GETTASKCOUNT         309
#define SYSCALL_EXISTTASK            310
#define SYSCALL_GETPROCESSORLOAD     311
#define SYSCALL_GETTASKGROUPID       312
#define SYSCALL_RETURNTASKGROUPID    313
#define SYSCALL_WAITGROUP            314
#define SYSCALL_NOTIFYONEINWAITGROUP 315
#define SYSCALL_NOTIFYALLINWAITGROUP 316
#define SYSCALL_JOINGROUP            317
#define SYSCALL_NOTIFYONEINJOINGROUP 318
#define SYSCALL_NOTIFYALLINJOINGROUP 319
#define SYSCALL_CREATETHREAD         320

/*** Syscall from sync.h ***/
#define SYSCALL_LOCK   400
#define SYSCALL_UNLOCK 401

/*** Syscall from dynamic_mem.h ***/
#define SYSCALL_MALLOC 500
#define SYSCALL_FREE   501

/*** Syscall from hdd.h ***/
#define SYSCALL_READHDDSECTOR  600
#define SYSCALL_WRITEHDDSECTOR 601

/*** Syscall from file_system.h ***/
#define SYSCALL_FOPEN      700
#define SYSCALL_FREAD      701
#define SYSCALL_FWRITE     702
#define SYSCALL_FSEEK      703
#define SYSCALL_FCLOSE     704
#define SYSCALL_REMOVE     705
#define SYSCALL_OPENDIR    706
#define SYSCALL_READDIR    707
#define SYSCALL_REWINDDIR  708
#define SYSCALL_CLOSEDIR   709
#define SYSCALL_ISFOPEN    710

/*** Syscall from serial_port.h ***/
#define SYSCALL_SENDSERIALDATA  800
#define SYSCALL_RECVSERIALDATA  801
#define SYSCALL_CLEARSERIALFIFO 802

/*** Syscall from mp_config_table.h ***/
#define SYSCALL_GETPROCESSORCOUNT 900

/*** Syscall from multiprocessor.h ***/
#define SYSCALL_GETAPICID 1000

/*** Syscall from window.h ***/
#define SYSCALL_GETBACKGROUNDWINDOWID    1100
#define SYSCALL_GETSCREENAREA            1101
#define SYSCALL_CREATEWINDOW             1102
#define SYSCALL_DELETEWINDOW             1103
#define SYSCALL_SHOWWINDOW               1104
#define SYSCALL_FINDWINDOWBYPOINT        1105
#define SYSCALL_FINDWINDOWBYTITLE        1106
#define SYSCALL_EXISTWINDOW              1107
#define SYSCALL_GETTOPWINDOWID           1108
#define SYSCALL_MOVEWINDOWTOTOP          1109
#define SYSCALL_ISPOINTINTITLEBAR        1110
#define SYSCALL_ISPOINTINCLOSEBUTTON     1111
#define SYSCALL_ISPOINTINRESIZEBUTTON    1112
#define SYSCALL_MOVEWINDOW               1113
#define SYSCALL_RESIZEWINDOW             1114
#define SYSCALL_GETWINDOWAREA            1115
#define SYSCALL_SENDEVENTTOWINDOW        1116
#define SYSCALL_RECVEVENTFROMWINDOW      1117
#define SYSCALL_UPDATESCREENBYID         1118
#define SYSCALL_UPDATESCREENBYWINDOWAREA 1119
#define SYSCALL_UPDATESCREENBYSCREENAREA 1120
#define SYSCALL_DRAWWINDOWBACKGROUND     1121
#define SYSCALL_DRAWWINDOWFRAME          1122
#define SYSCALL_DRAWWINDOWTITLEBAR       1123
#define SYSCALL_DRAWBUTTON               1124
#define SYSCALL_DRAWPIXEL                1125
#define SYSCALL_DRAWLINE                 1126
#define SYSCALL_DRAWRECT                 1127
#define SYSCALL_DRAWCIRCLE               1128
#define SYSCALL_DRAWTEXT                 1129
#define SYSCALL_BITBLT                   1130
#define SYSCALL_MOVEMOUSECURSOR          1131
#define SYSCALL_GETMOUSECURSORPOS        1132

/*** Syscall from jpeg.h ***/
#define SYSCALL_INITJPEG   1200
#define SYSCALL_DECODEJPEG 1201

/*** Syscall from util.h ***/
#define SYSCALL_GETTOTALRAMSIZE 1300
#define SYSCALL_GETTICKCOUNT    1301
#define SYSCALL_SLEEP           1302
#define SYSCALL_ISGRAPHICMODE   1303

/*** Syscall from loader.h ***/
#define SYSCALL_EXECUTEAPP 1400

/*** Syscall - test ***/
#define SYSCALL_TEST 0xFFFFFFFFFFFFFFFF

#endif // __SYSCALLNUMBERS_H__